language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y python-setuptools
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-scipy
  - sudo apt-get install -y libblas-dev
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y libatlas-dev
  - sudo apt-get install -y libatlas3gf-base
  - sudo apt-get install -y liblapack-dev
  - sudo apt-get install -y libatlas-base-dev
  - sudo apt-get install -y python3-minimal

install: "pip install -r requirements.txt"

script: python -m unittest discover
